[package]
authors = ["Christoph Groß <caemor@mailbox.org>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "An embedded-hal based driver for ePaper displays from Waveshare"
documentation = "https://docs.rs/epd-waveshare"
homepage = "https://github.com/caemor/epd-waveshare"
keywords = ["ePaper", "Display", "epd"]
license = "ISC"
name = "epd-waveshare"
readme = "README.md"
repository = "https://github.com/Caemor/epd_waveshare.git"
version = "0.2.0"
edition = "2018"

[badges]
# Travis CI: `repository` in format "<user>/<project>" is required.
# `branch` is optional; default is `master`
travis-ci = { repository = "caemor/epd-waveshare" }


[features]
default = ["epd1in54", "epd2in9", "epd4in2", "graphics"]

graphics = ["embedded-graphics"]
epd1in54 = []
epd2in9 = []
epd4in2 = []

[dependencies.embedded-graphics]
optional = true
version = "0.4.3"

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2.1"
